# Generated by Django 3.2.6 on 2023-01-24 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_uc', models.CharField(max_length=15)),
                ('numero_cliente', models.CharField(blank=True, max_length=15, null=True)),
                ('classificacao', models.CharField(choices=[('1', 'A4 HOROSAZONAL VERDE - Comercial'), ('2', 'B3 OUTROS-CONV. - Comercial')], max_length=3)),
                ('cnpj', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apps_clientes.clientes')),
            ],
        ),
    ]
