# Generated by Django 3.2.6 on 2023-01-24 04:07

import apps.faturas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura', models.FileField(upload_to=apps.faturas.models.diretorio_faturas)),
                ('mes_ano', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('uc_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apps_clientes.uc')),
            ],
        ),
    ]
