# Generated by Django 3.2.6 on 2023-02-11 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_faturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosFaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demnada_ativa_kw', models.FloatField()),
                ('demnada_ativa_rs', models.FloatField()),
                ('demanda_ativa_sem_icms_kw', models.FloatField()),
                ('demanda_ativa_sem_icms_rs', models.FloatField()),
                ('demanda_ultrapassagem_kw', models.FloatField()),
                ('demanda_ultrapassagem_rs', models.FloatField()),
                ('energia_atv_forn_ponta_te_kwh', models.FloatField()),
                ('energia_atv_forn_ponta_te_rs', models.FloatField()),
                ('energia_atv_forn_ponta_tusd_rs', models.FloatField()),
                ('energia_atv_forn_f_ponta_te_kwh', models.FloatField()),
                ('energia_atv_forn_f_ponta_te_rs', models.FloatField()),
                ('energia_atv_forn_f_ponta_tusd_rs', models.FloatField()),
                ('adicional', models.FloatField()),
                ('consumo_reativo_excedente_fp_kwh', models.FloatField()),
                ('consumo_reativo_excedente_fp_rs', models.FloatField()),
                ('consumo_reativo_excedente_np_kwh', models.FloatField()),
                ('consumo_reativo_excedente_np_rs', models.FloatField()),
                ('cip_ilum_pub_pref_municipal_rs', models.FloatField()),
                ('dic_rs', models.FloatField()),
                ('juros_moratorios_rs', models.FloatField()),
                ('multa_rs', models.FloatField()),
                ('icms', models.FloatField()),
                ('pis_pasep', models.FloatField()),
                ('cofins', models.FloatField()),
                ('faturamento', models.FloatField()),
                ('demanda_contratada', models.FloatField(blank=True, null=True)),
                ('fatura_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_faturas.faturas')),
            ],
        ),
    ]
