# Generated by Django 3.2.6 on 2023-02-11 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps_faturas', '0003_dadosfaturas_uc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosfaturas',
            name='mes_ano_fatura',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
