# Generated by Django 3.2.6 on 2023-02-11 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_faturas', '0004_dadosfaturas_mes_ano_fatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosfaturas',
            old_name='demnada_ativa_kw',
            new_name='demanda_ativa_kw',
        ),
        migrations.RenameField(
            model_name='dadosfaturas',
            old_name='demnada_ativa_rs',
            new_name='demanda_ativa_rs',
        ),
    ]
